name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build .so
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install gnome-software-dev

      - name: Build
        run: |
          make

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            build/libgs_plugin_vso.so