name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build .so
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dpkg --add-architecture arm64
          apt update
          apt install -y gnome-software gnome-software-dev meson gcc-aarch64-linux-gnu

      - name: Build
        run: |
          make
          mv build/libgs_plugin_vso.so libgs_plugin_vso_amd64.so
          make clean
          apt -o Dpkg::Options::="--force-overwrite" install -y gnome-software:arm64 gnome-software-dev:arm64
          make all-arm64
          mv build/libgs_plugin_vso.so libgs_plugin_vso_arm64.so

      - name: Calculate and Save Checksums
        run: sha256sum libgs_plugin_vso*.so >> checksums.txt

      - uses: actions/upload-artifact@v4
        with:
          name: gs-plugin-vso
          path: |
              checksums.txt
              libgs_plugin_vso*.so

      - uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            checksums.txt
            libgs_plugin_vso*.so
