name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build .so
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y gnome-software gnome-software-common gnome-software-dev meson

      - name: Build
        run: |
          make

      - name: Calculate and Save Checksums
        run: |
          sha256sum build/libgs_plugin_vso.so >> checksums.txt

      - uses: actions/upload-artifact@v4
        with:
          name: gs-plugin-vso
          path: |
              checksums.txt
              build/libgs_plugin_vso.so

      - uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            checksums.txt
            build/libgs_plugin_vso.so
